# golangci-lint v2 configuration
# See: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional recommended linters
    - bodyclose       # Check HTTP response body is closed
    - durationcheck   # Check for two durations multiplied together
    - errorlint       # Proper error wrapping
    - exhaustive      # Check switch statements are exhaustive
    - copyloopvar     # Check for loop variable captures
    # - gocritic        # Opinionated linter
    - gosec           # Security checker
    - misspell        # Spell checker
    - nilerr          # Check for nil error returns
    - prealloc        # Slice preallocation suggestions
    - sqlclosecheck   # Check SQL rows.Close() is called
    - unconvert       # Remove unnecessary type conversions

formatters:
  enable:
    - gofmt           # Code formatting
    - goimports       # Import ordering

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Don't check blank identifier assignments
    exclude-functions:
      - io.Copy
      - io.WriteString
      - (io.Closer).Close
      - (*os.File).Close
      - (*net/http.Response.Body).Close
      - (net/http.ResponseWriter).Write
      - (*bytes.Buffer).WriteString
      - (*bytes.Buffer).Write
      - (*strings.Builder).WriteString
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - (crypto/rand).Read
      - (*database/sql.Rows).Close
      - (*encoding/json.Decoder).Decode
      - (*encoding/json.Encoder).Encode

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Can be noisy

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
      - ifElseChain
      - commentedOutCode

  gosec:
    excludes:
      - G104  # Audit errors not checked
      - G304  # File path provided as taint input
      - G401  # Use of weak cryptographic primitive (MD5/SHA1)
      - G501  # Importing blocklisted package

  goimports:
    local-prefixes:
      - github.com/dhawalhost/wardseal

issues:
  exclude-rules:
    # Exclude linters from test files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    # Exclude from main.go files
    - path: cmd/.*/main\.go
      linters:
        - gocyclo
        - errcheck

    # Ignore generated files
    - path: \.pb\.go$
      linters:
        - all

    # Ignore defer close errors (common pattern)
    - linters:
        - errcheck
      text: "Error return value of .*.Close"

    # Ignore defer rows.Close errors
    - linters:
        - errcheck
      text: "Error return value of `rows.Close`"

    # Ignore rand.Read errors (used for non-crypto purposes)
    - linters:
        - errcheck
      text: "Error return value of `rand.Read`"

  max-issues-per-linter: 50
  max-same-issues: 5

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true
